name: focus_browser
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.20
  flutter_platform_widgets: ^6.0.0
  flutter_riverpod: ^2.4.5
  go_router: ^12.1.1
  http: ^1.1.2
  path_provider: ^2.1.1
  pull_down_button: ^0.9.3
  rxdart: ^0.27.7
  sembast: ^3.5.0+1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
